import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./providers/app-providers";
import { TooltipProvider } from "@/components/ui/tooltip";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-teal-400 to-yellow-200  flex items-center justify-center min-h-screen w-full max-sm:min-h-full `}
            >
                <NextTopLoader
                    color="#be123c"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={3}
                    crawl={true}
                    showSpinner={false}
                    easing="ease"
                    speed={200}
                    shadow="0 0 10px #22c55e,0 0 5px #22c55e"
                />
                <AppProviders>
                    <TooltipProvider>
                        <div className="flex flex-col w-full">
                            <div className="flex justify-center items-start gap-4 w-full">

                                <div className="card w-full max-w-4xl min-h-[700px] max-h-[95vh] bg-white dark:bg-[#232324] shadow-xl flex flex-col justify-between overflow-hidden max-sm:rounded-none max-sm:h-full rounded-lg m-2">
                                    {children}
                                </div>
                            </div>
                        </div>
                    </TooltipProvider>
                </AppProviders>
            </body>
        </html>
    );
}
